version: '3.8'

services:
  server:
    image: ghcr.io/maliksayyed/backend/dev-server
    container_name: server
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - decision

networks:
  decision:
    external: true